name: Linters
run-name: Linting with EsLint & StyleLint.
on: push
jobs:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: install
      run: npm install
    - name: ESLint
      run: npm run lint
    - name: Prettier
      run: npm run stylelint
